### ISSUE TITLE
Using an old version of Buffer's design system

### ISSUE THREAD

**Issue by gmzjuliana** [UIGuideline/UIGuideline#5]
**Describe the bug**
Uses an old version of Buffer's design system

**To Reproduce**
1. Go to Reference Systems
2. Scroll down to Buffer Design System
3. Click on Buffer Design System

**Expected behavior**
Expected to see updated versions of listed design systems but Buffer's example uses an old version

**Screenshots**
![image](https://user-images.githubusercontent.com/54291087/98824458-57b55180-2401-11eb-9948-8473d4c597c4.png)

**Additional context**
Our latest website is https://bufferapp.github.io/ui/ and it's up to date 😄

**Comment by sruda** [comment]
Hi @gmzjuliana first of all, thanks for writing to us.
That's good to know that Buffer has an updated version, we couldn't find it in our research about Buffer Design System.

It'll take time to replace the old reference since we have to pass through each component and update it, we're going to include it and remove the prev one though. 

I'm going to keep this issue open to let you know when we have already made the change.

Thanks again!.

**Comment by sruda** [comment]
Hi @gmzjuliana, we've updated Buffer System:
https://www.uiguideline.com/reference-systems/buffer-design-system

You can see the new website URL reference and all each component's URL updated as well.
Thanks for letting us know about this new version. ✌️
